# Generated by Django 2.0 on 2018-02-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlecontent',
            name='article',
        ),
        migrations.RemoveField(
            model_name='articlecontent',
            name='content',
        ),
        migrations.RemoveField(
            model_name='article',
            name='contents',
        ),
        migrations.AlterField(
            model_name='article',
            name='related_articles',
            field=models.ManyToManyField(null=True, related_name='_article_related_articles_+', to='blog.Article'),
        ),
        migrations.DeleteModel(
            name='ArticleContent',
        ),
    ]
