# Generated by Django 2.0 on 2018-02-25 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180225_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='contents',
            field=models.ManyToManyField(null=True, to='blog.TextContent'),
        ),
    ]
