# Generated by Django 2.0 on 2018-02-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_contents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textcontent',
            name='css_style',
            field=models.CharField(blank=True, choices=[('top', 'Top text'), ('h1', 'H1'), ('h2', 'H2'), ('text', 'Simple text'), ('numeric', 'Numeric list'), ('point', 'Point list'), ('marked-text', 'Left green border'), ('grey-text', 'Green text')], max_length=100, null=True),
        ),
    ]
