# Generated by Django 2.0 on 2018-02-26 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180226_0510'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='small_image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/'),
        ),
        migrations.AlterField(
            model_name='textcontent',
            name='css_style',
            field=models.CharField(blank=True, choices=[('short-article', 'Top text'), ('h1', 'H1'), ('h2', 'H2'), ('text', 'Simple text'), ('numeric', 'Numeric list'), ('point', 'Point list'), ('marked-text', 'Left green border'), ('grey-text', 'Green text')], max_length=100, null=True),
        ),
    ]
