# Generated by Django 2.0 on 2018-03-25 12:42

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180302_0541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='contents',
        ),
        migrations.AddField(
            model_name='article',
            name='contents',
            field=froala_editor.fields.FroalaField(blank=True),
        ),
    ]
