# Generated by Django 2.0 on 2018-03-25 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20180325_1242'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TextContent',
        ),
    ]
