# Generated by Django 2.0 on 2018-03-27 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20180325_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='last_mod',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.CharField(blank=True, help_text="Just text, without '/'", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='url',
            field=models.CharField(blank=True, help_text="Just text, without '/'", max_length=255, null=True),
        ),
    ]
