# Generated by Django 2.0 on 2018-03-28 17:54

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20180327_0440'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='intro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='contents',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
