# Generated by Django 2.0 on 2018-04-10 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='is_optimized',
            field=models.BooleanField(default=False),
        ),
    ]
