# Generated by Django 2.0 on 2018-05-21 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20180513_0440'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='header_background',
            field=models.ImageField(blank=True, null=True, upload_to='article_bg/'),
        ),
    ]
