# Generated by Django 2.0 on 2019-03-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='background',
            field=models.ImageField(blank=True, help_text='Background or some image', upload_to='backgrounds/'),
        ),
        migrations.AlterField(
            model_name='author',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
