# Generated by Django 2.0 on 2019-08-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20190319_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='hidden_link',
            field=models.BooleanField(default=False),
        ),
    ]
