# Generated by Django 2.0 on 2018-11-01 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_contactform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactform',
            name='callback',
        ),
        migrations.RemoveField(
            model_name='contactform',
            name='reason',
        ),
    ]
