# Generated by Django 2.0 on 2018-02-24 15:54

from django.db import migrations, models
import project.cms.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_customerlogo'),
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerLogoComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('logos', models.ManyToManyField(to='content.CustomerLogo')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, project.cms.models.Component),
        ),
    ]
