# Generated by Django 2.0 on 2018-02-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_project'),
        ('cms', '0003_projectcomponent'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcomponent',
            name='projects',
            field=models.ManyToManyField(to='content.Project'),
        ),
    ]
