# Generated by Django 2.0 on 2018-02-24 17:47

from django.db import migrations, models
import project.cms.models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_projectcomponent_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeSpaceComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, project.cms.models.Component),
        ),
    ]
