# Generated by Django 2.0 on 2018-02-24 18:19

from django.db import migrations, models
import project.cms.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_column_css_icon'),
        ('cms', '0005_officespacecomponent'),
    ]

    operations = [
        migrations.CreateModel(
            name='TileComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('css_style', models.CharField(choices=[(1, 'Thin'), (2, 'Fat')], default=1, max_length=255)),
                ('columns', models.ManyToManyField(to='content.Column')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, project.cms.models.Component),
        ),
    ]
