# Generated by Django 2.0 on 2018-02-24 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_tilecomponent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tilecomponent',
            name='css_style',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Thin'), (2, 'Fat')], default=1, max_length=255),
        ),
    ]
