# Generated by Django 2.0 on 2018-02-24 18:52

from django.db import migrations, models
import project.cms.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_teammember'),
        ('cms', '0007_auto_20180224_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('members', models.ManyToManyField(to='content.TeamMember')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, project.cms.models.Component),
        ),
        migrations.AlterField(
            model_name='tilecomponent',
            name='css_style',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Thin'), (2, 'Fat')], default=1),
        ),
    ]
