# Generated by Django 2.0 on 2018-02-24 19:20

from django.db import migrations, models
import project.cms.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_columnimage'),
        ('cms', '0008_auto_20180224_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnImageComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('columns', models.ManyToManyField(to='content.ColumnImage')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, project.cms.models.Component),
        ),
    ]
