# Generated by Django 2.0 on 2018-02-24 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_columnimagecomponent'),
    ]

    operations = [
        migrations.AddField(
            model_name='fourcolumncomponent',
            name='css_style',
            field=models.CharField(blank=True, choices=[('default', 'default'), ('grey', 'grey')], max_length=50, null=True),
        ),
    ]
