# Generated by Django 2.0 on 2018-02-25 05:22

from django.db import migrations, models
import project.cms.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_auto_20180225_0522'),
        ('cms', '0010_fourcolumncomponent_css_style'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextImageComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('galleries', models.ManyToManyField(to='content.TextImage')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, project.cms.models.Component),
        ),
        migrations.AlterField(
            model_name='fourcolumncomponent',
            name='background',
            field=models.ImageField(help_text='Background or some image', upload_to='backgrounds/'),
        ),
        migrations.AlterField(
            model_name='headercomponent',
            name='background',
            field=models.ImageField(help_text='Background or some image', upload_to='backgrounds/'),
        ),
    ]
