# Generated by Django 2.0 on 2018-02-25 05:57

from django.db import migrations, models
import project.cms.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_auto_20180225_0557'),
        ('cms', '0011_auto_20180225_0522'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnImageWithListComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('items', models.ManyToManyField(to='content.ColumnImageWithList')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, project.cms.models.Component),
        ),
    ]
