# Generated by Django 2.0 on 2018-02-25 06:35

from django.db import migrations, models
import project.cms.models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_columnimagewithlistcomponent'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextWithBigBackgroundComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('button_title', models.CharField(blank=True, max_length=50, null=True)),
                ('button_url', models.CharField(blank=True, max_length=255, null=True)),
                ('background', models.ImageField(help_text='Background or some image', upload_to='backgrounds/')),
                ('css_style', models.PositiveSmallIntegerField(choices=[(1, 'White title'), (2, 'Green title'), (3, 'With ico buttons')], default=1)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, project.cms.models.Component),
        ),
    ]
