# Generated by Django 2.0 on 2018-02-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_textwithbigbackgroundcomponent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headercomponent',
            name='css_style',
            field=models.PositiveSmallIntegerField(choices=[(1, 'As on main page'), (2, 'With white menu links'), (3, 'With black menu links'), (4, 'With contact form')]),
        ),
    ]
