# Generated by Django 2.0 on 2018-02-26 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0015_auto_20180226_0510'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='show_breadcrumbs',
            field=models.BooleanField(default=False),
        ),
    ]
