# Generated by Django 2.0 on 2018-02-26 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_page_show_breadcrumbs'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecomponent',
            name='button_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='articlecomponent',
            name='button_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
