# Generated by Django 2.0 on 2018-03-01 18:44

from django.db import migrations, models
import django.db.models.deletion
import project.cms.models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0017_auto_20180226_0554'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Blog component is a singleton.', max_length=255)),
            ],
            bases=(models.Model, project.cms.models.Component),
        ),
        migrations.AlterField(
            model_name='headercomponent',
            name='css_style',
            field=models.PositiveSmallIntegerField(choices=[(1, 'As on main page'), (2, 'With white menu links'), (3, 'With black menu links'), (4, 'With contact form'), (5, 'Without uppercase')]),
        ),
        migrations.AlterField(
            model_name='page',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Blog category related to this page', null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Category'),
        ),
    ]
