# Generated by Django 2.0 on 2018-03-02 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0018_auto_20180301_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='show_on_category_menu',
            field=models.BooleanField(default=False),
        ),
    ]
