# Generated by Django 2.0 on 2018-03-02 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180226_0554'),
        ('cms', '0019_page_show_on_category_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomponent',
            name='title',
        ),
        migrations.AddField(
            model_name='blogcomponent',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Category'),
        ),
    ]
