# Generated by Django 2.0 on 2018-03-02 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_auto_20180302_0513'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_marked_category',
            field=models.BooleanField(default=False, help_text='Will add extra css styles for this category'),
        ),
    ]
