# Generated by Django 2.0 on 2018-03-02 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0021_page_is_marked_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='is_marked_category',
        ),
    ]
