# Generated by Django 2.0 on 2018-03-04 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0023_page_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomponent',
            name='title',
            field=models.CharField(default='Blog', max_length=255),
            preserve_default=False,
        ),
    ]
