# Generated by Django 2.0 on 2018-03-04 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_city_more_text'),
        ('cms', '0024_blogcomponent_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TextImageComponent',
            new_name='GalleryComponent',
        ),
    ]
