# Generated by Django 2.0 on 2018-03-04 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0025_auto_20180304_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallerycomponent',
            name='galleries',
        ),
        migrations.DeleteModel(
            name='GalleryComponent',
        ),
    ]
