# Generated by Django 2.0 on 2018-03-04 09:16

from django.db import migrations, models
import project.cms.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_city_more_text'),
        ('cms', '0026_auto_20180304_0916'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('galleries', models.ManyToManyField(to='content.TextImage')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, project.cms.models.Component),
        ),
    ]
