# Generated by Django 2.0 on 2018-03-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0027_gallerycomponent'),
    ]

    operations = [
        migrations.AddField(
            model_name='tilecomponent',
            name='column_count',
            field=models.CharField(choices=[('col-xs-4', 'Three columns'), ('col-xs-6', 'Two columns')], default='col-xs-4', max_length=50),
        ),
    ]
