# Generated by Django 2.0 on 2018-03-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0028_tilecomponent_column_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tilecomponent',
            name='column_count',
            field=models.CharField(choices=[('col-md-4 col-sm-6 col-xs-12', 'Three columns'), ('col-md-6 col-sm-6 col-xs-12', 'Two columns')], default='col-xs-4', max_length=50),
        ),
    ]
