# Generated by Django 2.0 on 2018-03-12 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0030_auto_20180310_0819'),
    ]

    operations = [
        migrations.CreateModel(
            name='JsCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('js_code', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='page',
            name='js_code',
        ),
        migrations.AddField(
            model_name='jscode',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Page'),
        ),
    ]
