# Generated by Django 2.0 on 2018-03-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0031_auto_20180312_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='jscode',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
