# Generated by Django 2.0 on 2018-03-25 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0032_jscode_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlecomponent',
            name='article',
        ),
        migrations.RemoveField(
            model_name='blogcomponent',
            name='category',
        ),
        migrations.RemoveField(
            model_name='page',
            name='category',
        ),
        migrations.RemoveField(
            model_name='page',
            name='show_on_category_menu',
        ),
        migrations.DeleteModel(
            name='ArticleComponent',
        ),
    ]
