# Generated by Django 2.0 on 2018-04-02 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0034_auto_20180325_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='headercomponent',
            name='css_subtitle_style',
            field=models.CharField(blank=True, choices=[('h-green-title', 'Green color'), ('h-grey-title', 'Grey color'), ('h-black-title', 'Dark color')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='headercomponent',
            name='css_title_style',
            field=models.CharField(blank=True, choices=[('h-green-title', 'Green color'), ('h-grey-title', 'Grey color'), ('h-black-title', 'Dark color')], max_length=100, null=True),
        ),
    ]
