# Generated by Django 2.0 on 2018-05-02 05:09

from django.db import migrations, models
import project.cms.models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0035_auto_20180402_0856'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFormComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, project.cms.models.Component),
        ),
        migrations.AlterField(
            model_name='headercomponent',
            name='css_subtitle_style',
            field=models.CharField(blank=True, choices=[('h-green-title', 'Green color'), ('h-grey-title', 'Grey color'), ('h-black-title', 'Dark color'), ('h-white-title', 'White color')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='headercomponent',
            name='css_title_style',
            field=models.CharField(blank=True, choices=[('h-green-title', 'Green color'), ('h-grey-title', 'Grey color'), ('h-black-title', 'Dark color'), ('h-white-title', 'White color')], max_length=100, null=True),
        ),
    ]
