# Generated by Django 2.0 on 2018-05-13 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0036_auto_20180502_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headercomponent',
            name='css_style',
            field=models.PositiveSmallIntegerField(choices=[(1, 'As on main page'), (6, 'As on main page with white links'), (2, 'With white menu links'), (3, 'With black menu links'), (4, 'With contact form'), (5, 'Without uppercase')]),
        ),
    ]
