# Generated by Django 2.0 on 2018-05-22 15:25

from django.db import migrations, models
import django.db.models.deletion
import project.cms.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_project_nofollow_link'),
        ('cms', '0037_auto_20180513_0440'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPageComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.ImageField(help_text='Background or some image', upload_to='backgrounds/')),
                ('project_url', models.CharField(max_length=250)),
                ('header_text', models.TextField()),
                ('location_text', models.CharField(max_length=50)),
                ('industry_text', models.CharField(max_length=50)),
                ('team_size_text', models.CharField(max_length=50)),
                ('period_text', models.CharField(max_length=50)),
                ('achievements', models.ManyToManyField(to='content.ListItem')),
                ('facts', models.ManyToManyField(to='content.Column')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.Project')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, project.cms.models.Component),
        ),
        migrations.AddField(
            model_name='columnimagewithlistcomponent',
            name='css_style',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Image as background'), (2, 'Image left')], default=1),
        ),
        migrations.AddField(
            model_name='columnimagewithlistcomponent',
            name='items_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
