# Generated by Django 2.0 on 2018-05-22 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0038_auto_20180522_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='columnimagewithlistcomponent',
            name='items_title',
        ),
    ]
