# Generated by Django 2.0 on 2018-05-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0039_remove_columnimagewithlistcomponent_items_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpagecomponent',
            name='title',
            field=models.CharField(default='-', max_length=255),
            preserve_default=False,
        ),
    ]
