# Generated by Django 2.0 on 2018-05-31 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0040_projectpagecomponent_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='show_on_sitemap',
            field=models.BooleanField(default=True),
        ),
    ]
