# Generated by Django 2.0 on 2018-05-31 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0041_page_show_on_sitemap'),
    ]

    operations = [
        migrations.CreateModel(
            name='RobotsFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
