# Generated by Django 2.0 on 2018-07-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0042_robotsfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedirectSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_from', models.CharField(max_length=255)),
                ('url_to', models.CharField(max_length=255)),
            ],
        ),
    ]
