# Generated by Django 2.0 on 2018-07-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0043_redirectsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='redirectsettings',
            options={'verbose_name_plural': 'Redirect Settings'},
        ),
        migrations.AlterField(
            model_name='redirectsettings',
            name='url_from',
            field=models.CharField(help_text='Example, /url-from/', max_length=255),
        ),
        migrations.AlterField(
            model_name='redirectsettings',
            name='url_to',
            field=models.CharField(help_text='Example, /url-to/', max_length=255),
        ),
    ]
