# Generated by Django 2.0 on 2018-10-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0044_auto_20180719_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottomcomponent',
            name='view_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Default'), (2, 'Big size')], default=1),
        ),
    ]
