# Generated by Django 2.0 on 2018-10-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0045_auto_20181015_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='technologycomponent',
            name='background',
            field=models.ImageField(blank=True, help_text='Background or some image', null=True, upload_to='tech_backgrounds/'),
        ),
        migrations.AlterField(
            model_name='projectpagecomponent',
            name='facts',
            field=models.ManyToManyField(blank=True, to='content.Column'),
        ),
    ]
