# Generated by Django 2.0 on 2018-11-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0047_projectpagecomponent_technology_component'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citycomponent',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='gallerycomponent',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='projectcomponent',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
