# Generated by Django 2.0 on 2019-01-30 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0050_auto_20181118_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tilecomponent',
            name='css_style',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Thin'), (2, 'Fat'), (3, 'Icons centered')], default=1),
        ),
    ]
