# Generated by Django 2.0 on 2019-01-30 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0051_auto_20190130_0618'),
    ]

    operations = [
        migrations.AddField(
            model_name='fourcolumncomponent',
            name='columns_count',
            field=models.CharField(choices=[('Four columns', 'col-md-3 col-sm-6 col-xs-12'), ('Tree columns', 'col-sm-4 col-xs-12')], default='col-md-3 col-sm-6 col-xs-12', max_length=50),
        ),
    ]
