# Generated by Django 2.0 on 2019-01-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0052_fourcolumncomponent_columns_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fourcolumncomponent',
            name='columns_count',
            field=models.CharField(choices=[('col-md-3 col-sm-6 col-xs-12', 'Four columns'), ('col-sm-4 col-xs-12', 'Tree columns')], default='col-md-3 col-sm-6 col-xs-12', max_length=50),
        ),
    ]
