# Generated by Django 2.0 on 2019-02-04 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0055_columnimagecomponent_columns_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='custom_css',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bottomcomponent',
            name='view_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Default'), (2, 'Big size'), (3, 'Fixed on the bottom')], default=1),
        ),
    ]
