# Generated by Django 2.0 on 2019-02-13 05:43

from django.db import migrations, models
import project.cms.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_iconlink_review'),
        ('cms', '0056_auto_20190204_0537'),
    ]

    operations = [
        migrations.CreateModel(
            name='IconComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('css_class', models.CharField(default='col-xs-2', max_length=70)),
                ('icon_list', models.ManyToManyField(to='content.IconLink')),
            ],
            bases=(models.Model, project.cms.models.Component),
        ),
        migrations.CreateModel(
            name='ReviewsComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('review_list', models.ManyToManyField(to='content.Review')),
            ],
            bases=(models.Model, project.cms.models.Component),
        ),
    ]
