# Generated by Django 2.0 on 2019-02-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0057_iconcomponent_reviewscomponent'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewscomponent',
            name='button_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reviewscomponent',
            name='button_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
