# Generated by Django 2.0 on 2019-02-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0058_auto_20190213_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iconcomponent',
            name='css_class',
            field=models.CharField(default='col-sm-2', max_length=70),
        ),
    ]
