# Generated by Django 2.0 on 2019-02-18 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0059_auto_20190213_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='iconcomponent',
            name='button_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='iconcomponent',
            name='button_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
