# Generated by Django 2.0 on 2019-02-21 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0060_auto_20190218_0618'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpagecomponent',
            name='projects_page_url',
            field=models.CharField(default='/projects/', max_length=200),
        ),
    ]
