# Generated by Django 2.0 on 2019-03-01 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0061_projectpagecomponent_projects_page_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columnimagewithlistcomponent',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='columnimagewithlistcomponent',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='gallerycomponent',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
