# Generated by Django 2.0 on 2019-03-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0062_auto_20190301_0517'),
    ]

    operations = [
        migrations.AddField(
            model_name='iconcomponent',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to='icons_set/'),
        ),
    ]
