# Generated by Django 2.0 on 2019-03-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0063_iconcomponent_background'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iconcomponent',
            name='background',
        ),
        migrations.AlterField(
            model_name='headercomponent',
            name='sub_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
