# Generated by Django 2.0 on 2019-03-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0064_auto_20190312_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='iconcomponent',
            name='background',
            field=models.ImageField(default='', help_text='Background or some image', upload_to='backgrounds/'),
            preserve_default=False,
        ),
    ]
