# Generated by Django 2.0 on 2019-03-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0065_iconcomponent_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columnimagecomponent',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contactformcomponent',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='customerlogocomponent',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='fourcolumncomponent',
            name='background',
            field=models.ImageField(blank=True, help_text='Background or some image', upload_to='backgrounds/'),
        ),
        migrations.AlterField(
            model_name='fourcolumncomponent',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='headercomponent',
            name='background',
            field=models.ImageField(blank=True, help_text='Background or some image', upload_to='backgrounds/'),
        ),
        migrations.AlterField(
            model_name='iconcomponent',
            name='background',
            field=models.ImageField(blank=True, help_text='Background or some image', upload_to='backgrounds/'),
        ),
        migrations.AlterField(
            model_name='officespacecomponent',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='projectpagecomponent',
            name='background',
            field=models.ImageField(blank=True, help_text='Background or some image', upload_to='backgrounds/'),
        ),
        migrations.AlterField(
            model_name='teamcomponent',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='technologycomponent',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='textwithbigbackgroundcomponent',
            name='background',
            field=models.ImageField(blank=True, help_text='Background or some image', upload_to='backgrounds/'),
        ),
        migrations.AlterField(
            model_name='textwithbigbackgroundcomponent',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tilecomponent',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
