# Generated by Django 2.0 on 2019-03-27 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0066_auto_20190319_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columnimagewithlistcomponent',
            name='columns_count',
            field=models.CharField(choices=[('col-md-6', 'Two columns'), ('col-md-4 col-sm-6 col-xs-12', 'Tree columns'), ('col-md-3 col-sm-6 col-xs-12', 'Four columns')], default='col-md-6 col-sm-6', max_length=50),
        ),
    ]
