# Generated by Django 2.0 on 2019-03-27 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0067_auto_20190327_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columnimagecomponent',
            name='columns_count',
            field=models.CharField(choices=[('col-md-6', 'Two columns'), ('col-md-4 col-sm-6 col-xs-12', 'Tree columns'), ('col-md-3 col-sm-6 col-xs-12', 'Four columns')], default='col-md-6 col-sm-6', max_length=50),
        ),
        migrations.AlterField(
            model_name='fourcolumncomponent',
            name='columns_count',
            field=models.CharField(choices=[('col-md-3 col-sm-6 col-xs-12', 'Four columns'), ('col-md-4 col-sm-6 col-xs-12', 'Tree columns')], default='col-md-3 col-sm-6 col-xs-12', max_length=50),
        ),
    ]
