# Generated by Django 2.0 on 2018-02-24 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20180224_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='css_icon',
            field=models.CharField(blank=True, choices=[('development', 'development'), ('high-load', 'high-load'), ('security', 'security'), ('mach-learning', 'mach-learning'), ('dev-ops', 'dev-ops'), ('real-time', 'real-time')], max_length=255, null=True),
        ),
    ]
