# Generated by Django 2.0 on 2018-02-24 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('button_title', models.CharField(blank=True, max_length=50, null=True)),
                ('button_url', models.CharField(blank=True, max_length=255, null=True)),
                ('background', models.ImageField(upload_to='backgrounds/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
