# Generated by Django 2.0 on 2018-02-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_columnimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='css_icon',
            field=models.CharField(blank=True, choices=[('development', 'development'), ('high-load', 'high-load'), ('security', 'security'), ('mach-learning', 'mach-learning'), ('dev-ops', 'dev-ops'), ('real-time', 'real-time'), ('back-end', 'back-end'), ('front-end', 'front-end'), ('devops', 'devops'), ('qa', 'qa'), ('ux', 'ux'), ('intergations', 'intergations')], max_length=255, null=True),
        ),
    ]
