# Generated by Django 2.0 on 2018-02-25 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_auto_20180224_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('background', models.ImageField(help_text='Background or some image', upload_to='backgrounds/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='city',
            name='background',
            field=models.ImageField(help_text='Background or some image', upload_to='backgrounds/'),
        ),
        migrations.AlterField(
            model_name='columnimage',
            name='background',
            field=models.ImageField(help_text='Background or some image', upload_to='backgrounds/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='background',
            field=models.ImageField(help_text='Background or some image', upload_to='backgrounds/'),
        ),
    ]
