# Generated by Django 2.0 on 2018-02-25 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_auto_20180225_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='css_icon',
            field=models.CharField(blank=True, choices=[('development', 'development'), ('high-load', 'high-load'), ('security', 'security'), ('mach-learning', 'mach-learning'), ('dev-ops', 'dev-ops'), ('real-time', 'real-time'), ('back-end', 'back-end'), ('front-end', 'front-end'), ('devops', 'devops'), ('qa', 'qa'), ('ux', 'ux'), ('intergations', 'intergations'), ('ico manufacturing', 'ico manufacturing'), ('ico oli & gas', 'ico oli & gas'), ('ico real', 'ico real estate'), ('ico jems', 'ico jems'), ('ico chemical', 'ico chemical'), ('ico agriculture', 'ico agriculture')], max_length=255, null=True),
        ),
    ]
