# Generated by Django 2.0 on 2018-02-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_auto_20180225_0635'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='more_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
