# Generated by Django 2.0 on 2018-03-11 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_city_more_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='hover_background',
            field=models.ImageField(blank=True, null=True, upload_to='hover-bg/'),
        ),
        migrations.AddField(
            model_name='column',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
