# Generated by Django 2.0 on 2018-05-16 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_auto_20180311_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='nofollow_link',
            field=models.BooleanField(default=True),
        ),
    ]
