# Generated by Django 2.0 on 2018-05-22 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_project_nofollow_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='columnimagewithlist',
            name='items_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
