# Generated by Django 2.0 on 2018-11-13 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_columnimagewithlist_items_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerlogo',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
