# Generated by Django 2.0 on 2019-02-13 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_customerlogo_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='IconLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('icon', models.ImageField(upload_to='icons_set/')),
                ('link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='review_user/')),
                ('text', models.TextField()),
                ('url', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
