# Generated by Django 2.0 on 2019-02-21 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_auto_20190220_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='background_color',
            field=models.CharField(default='#fff', max_length=50),
        ),
    ]
