# Generated by Django 2.0 on 2019-03-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0022_auto_20190301_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iconlink',
            name='background',
        ),
        migrations.AddField(
            model_name='iconlink',
            name='icon',
            field=models.ImageField(default='', upload_to='icons_set/'),
            preserve_default=False,
        ),
    ]
