# Generated by Django 2.0 on 2019-03-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0024_iconlink_background'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iconlink',
            name='background',
        ),
        migrations.AlterField(
            model_name='iconlink',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icons_set/'),
        ),
    ]
