# Generated by Django 2.0 on 2019-03-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0026_auto_20190318_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='background',
            field=models.ImageField(blank=True, help_text='Background or some image', upload_to='backgrounds/'),
        ),
        migrations.AlterField(
            model_name='city',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='column',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='columnimage',
            name='background',
            field=models.ImageField(blank=True, help_text='Background or some image', upload_to='backgrounds/'),
        ),
        migrations.AlterField(
            model_name='columnimage',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='columnimagewithlist',
            name='background',
            field=models.ImageField(blank=True, help_text='Background or some image', upload_to='backgrounds/'),
        ),
        migrations.AlterField(
            model_name='columnimagewithlist',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='background',
            field=models.ImageField(blank=True, help_text='Background or some image', upload_to='backgrounds/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='textimage',
            name='background',
            field=models.ImageField(blank=True, help_text='Background or some image', upload_to='backgrounds/'),
        ),
        migrations.AlterField(
            model_name='textimage',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
